### ISSUE TITLE
Behaviour when an invalid UUID or invalid user is given in the URL

### ISSUE THREAD

**Issue by chrisapplegate** [yunojuno/django-visitor-pass#7]
Referencing this issue: https://github.com/yunojuno/django-user-visit/issues/14 and continuing it here.

Two proposed fixes in that issue:

1. Add code in `VisitorRequestMiddleware` to handle the case when there is an invalid UUID is given in the URL, as it currently allows a ValidationError to full bubble up and give a code 500 error.
2. Possibly update the case when a UUID has been given for a valid but expired Visitor, returning a code 403 (although this could be considered a breaking change)

**Comment by hugorodgerbrown** [comment]
Huh - I thought I'd be clever and open this project in Codespaces - which I thought would open a new branch, but it doesn't. So it appears I've pushed my fix to master.

**Comment by hugorodgerbrown** [comment]
Commit: https://github.com/yunojuno/django-visitor-pass/commit/fdd7ff97b2cf32137751582ac5ae3e8d50f03542

**Comment by hugorodgerbrown** [comment]
In other news - Codespaces is really very impressive.

**Comment by chrisapplegate** [comment]
This works great! Could it get pushed to a new release version (0.4.1?)

**Comment by hugorodgerbrown** [comment]
Pushed as v0.5 (as technically someone may be handling the 500 in such a way that this causes an issue).

Thanks for bringing this up - I've added a reference to this issue in the `CHANGELOG`.
